vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
       products_images:
           uri_prefix: /images/products_images
           upload_destination: '%kernel.project_dir%/public/images/images-produits'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
